sindresorhus/electron-dl

index.js
readme.md

Added to allow working around #3, and also nice to have the option.

Add a `saveAs` option to prompt a dialog instead of downloading immediately

---

index.js
readme.md

Hi there!
I have a use case for programmatically triggering downloads and then processing each downloaded file in-place.
With that in mind, this is what I came up with. `download()` now returns a `Promise` that resolves with the completed `DownloadItem`.

Make download() return a Promise

---

index.js
package.json
readme.md

I've added 4 new options for the config object.
- `onProgress` a callback to receive the download progress ratio
- `onComplete` a callback to let know the user when the download has finished
- `errorTitle` the title of the error dialog
- `errorMessage` the message of the error dialog
For `errorMessage` there is no way of passing a template literal (since it's interpreted when the string is created) so I had to use `string.replace(...)`.

New options for localization and callbacks

---

index.js

Hello @sindresorhus!   Thank you for an awesome module!
I have an electron app with multiple windows and I've found that when I configure it following the readme like this:
```
require('electron-dl')();
```
If I close a window and then download a file in a separate window I receive the following error:
I believe this is because `win.setProgressBar(ratio);` is being called on the destroyed window.  I've added the same check you placed in the 'done' event handler to fix it.
If you think there is a better way to handle this without updating the library I'm all ears!
Thank you,
Nick

Prevent “Object destroyed” error after closing a window

---

index.js
readme.md

by add a new option `filename`

Allow user to control the filename

---

.gitignore
index.js
readme.md

A new option ```showBadge``` has been added. It defaults to true. If it is false, no badge count will be shown on dock icon for macOS and Linux while downloads are active.
Closes #40 
Fixes #39

Add `showBadge` option

---

.gitignore
index.js

If one choose to use saveAs behaviour and the user downloads a file for the second time, the code for opening that file after the download has completed does not work. This fix will always use name of the actual file that was downloaded, not some initial variable set up front.

Fix problem where folder would not open if one replaces an existing file

---

index.js
readme.md

This fixes #10 and is related to #25.
This adds a callback `onStarted` that gives the download item. This is a non-intrusive enhancement that enables developers to handle advanced situations such as canceling a download.
This also updates removing the listener when the item is done. Before it would only be removed if `completed`. Now the listener will be removed when canceled or interrupted as well.

Exposed download item to allow canceling

---

index.js
readme.md

It will be useful to have a callback in-case user cancels the download in saveAs option...
eg. useful for managing download spinner on download button.

Optional callback for cancelled state of download

---

index.d.ts
index.js
index.test-d.ts
package.json

Alright, gotta get started on those Caprine dependencies. Went through [the checklist](https://github.com/sindresorhus/typescript-definition-style-guide), hope I didn't miss anything.
One question: in Options, `directory` and `filename` do have "default values", but those aren't basic types, just a description. Should that be marked with `@default`?
---
Closes #69

Add TypeScript definition

---

readme.md

The progress value is not each individual download but all the current downloads, at least based on my experience with it (I might be doing something wrong).
So, if you download 3 items, you can't get the download progress of each individual file but instead for the total downloads.

Update `onProgress` docs

---

index.d.ts
index.js
readme.md

Adds the `fullProgressUpdate` option. When true, the `onProgress` callback receives an object containing additional information about transferred and total bytes, instead of only the percentage.
```
{
percent: 0.1,
transferredBytes: 1024,
totalBytes: 10240
}
```

Expose full progress info instead of only percentage

---

index.js
test/index.js

Clear this warning message:
> (electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.

Remove Electron warning

---

index.js

Fix `openFolderWhenDone` sometimes selecting the wrong file

---

index.js

Inspired by #112 
If a downloaded file is renamed via [unused-filename](https://github.com/sindresorhus/unused-filename/) (`file.txt` → `file (1).txt`), the error message for interrupted download will show the non-renamed filename. I believe showing the renamed filename is more helpful.

Improve error message for interrupted download

---

index.d.ts
index.js
readme.md

This continues from #101 .
Moved error handling into `electronDl()`, therefore `electronDl.download()` will not pop up error dialog.

Don't show error dialog when download is interrupted in `electronDl.download()`

---

index.js

The current implementation ignores the filename when using the option saveAs.
This PR will fix the above issue and will set the saveDialogOptions default path to the file path given.
Referenced issues: 
Fixes #59
Fixes #79

Fix ignored filename when using `saveAs` option

---

index.d.ts
index.js
readme.md

In our app we are not currently using electron-dl, but electron-context-menu. using save image was breaking because electron-dl wasn't able to find the window.
This patch fixes that problem.
Unfortunately there can be many windows and several browserviews attached to each, so we need to iterate to find the right one as there is not a way to ask electron for it.

Add support for `BrowserView`

---

index.d.ts
index.js
readme.md

I am using electron-dl with `electronDl();` and `win.webContents.downloadURL(url);` and needed a way to get the total progress of all download files and a callback when a file is finished to display a notification.
I am not 100% certain this is the best way to solve this problem so feel free to close this pull request but I think it might be useful for other people as well and it fixes #110.

Add `onCompleted` and `onTotalProgress` options

---

package.json

Running `npx tsd` with 0.11.0 raises
```
node_modules/electron/electron.d.ts:1657:30
✖  1657:30  Cannot extend an interface NodeJS.EventEmitter. Did you mean implements?  
✖  2994:30  Cannot extend an interface NodeJS.EventEmitter. Did you mean implements? 
...
18 errors
```
but upgrading to 0.17.0 fixes these problems, and runs with no errors/warnings.
Not sure what the original Electron issue was that was preventing TSD running, but it seems to work properly now.

Enable TSD again

---

index.d.ts
index.js
package.json
readme.md

Based on #73, but incorporated feedback.
Fixes #106.

Add `overwrite` option

---

index.d.ts
index.js
readme.md

Sometimes we don't want to show the progress bar while downloading, so I make it as an option.

Add `showProgressBar` option

---

index.d.ts
index.js
readme.md

Apologies in advance if this is the incorrect procedure, just wanted to get this PR through since the original (#153) appears to have gone stale. I've made amendments based on the review on that PR.
Closes #153

Dialog options [continuation and fix of #153]

---

index.d.ts
index.js
readme.md

based on #142 
fixes #115 
also it was not possible to call `item.cancel()` from `onStart` because of wrong code order

await download() will not stuck if item.cancel() was called
